In [1]:
"""Assign your Name to variable name and Age to variable age. Make a Python
program that prints your name and age."""
name="DINESH KUMAR.S"
age="20"
print("Name:{0} ".format(name))
print("Age: {0}".format(age))

Name:DINESH KUMAR.S 
Age: 20


In [2]:
"""2. X="Datascience is used to extract meaningful insights." Split the string"""
X="Datascience is used to extract meaningful insights."
q2=X.split()
print(q2)

['Datascience', 'is', 'used', 'to', 'extract', 'meaningful', 'insights.']


In [3]:
"""3. Make a function that gives multiplication of two numbers"""
def prod(para1,para2):
 ans=para1*para2
 return ans
var1=int(input("Number 1:"))
var2=int(input("Number 2:"))
ans=prod(var1,var2)
print("The product of the the numbers {0} and {1} is {2}".format(var1,var2,ans))

Number 1:5
Number 2:5
The product of the the numbers 5 and 5 is 25


In [4]:
"""4. Create a Dictionary of 5 States with their capitals. also print the keys and values."""
indstates={"Tamil Nadu":"Chennai","Kerala":"Thiruvananthapuram","Karnataka":"Bangalore",
 "Maharashtra":"Mumbai","Uttar Pradesh":"Lucknow"}
q4a=indstates.keys()
q4b=indstates.values()
print("Dictionary keys: {0}".format(q4a))
print("Dictionary values: {0}".format(q4b))

Dictionary keys: dict_keys(['Tamil Nadu', 'Kerala', 'Karnataka', 'Maharashtra', 'Uttar Pradesh'])
Dictionary values: dict_values(['Chennai', 'Thiruvananthapuram', 'Bangalore', 'Mumbai', 'Lucknow'])


In [5]:
"""5. Create a list of 1000 numbers using range function."""
q5=[x for x in range(0,1001)]
print(q5)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,

In [6]:
"""6. Create an identity matrix of dimension 4 by 4"""
import numpy as np
q6=np.identity(4)
print("identity matrix {0}:\n".format(q6))

identity matrix [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]:



In [7]:
"""7. Create a 3x3 matrix with values ranging from 1 to 9"""
q7a=np.arange(1,10)
q7b=q7a.reshape(3,3)
print(q7b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
"""8. Create 2 similar dimensional array and perform sum on them."""
q8a=np.arange(5,14).reshape(3,3)
q8b=np.arange(6,15).reshape(3,3)
print("array 1")
print(q8a)
print("array 2")
print(q8b)
q8c=q8a+q8b
print("summed array")
print(q8c)

array 1
[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]
array 2
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
summed array
[[11 13 15]
 [17 19 21]
 [23 25 27]]


In [9]:
"""9. Generate the series of dates from 1st Feb, 2023 to 1st March, 2023 (both
inclusive)"""
import pandas as pd
from datetime import datetime, timedelta
q9a=datetime(2023,2,1)
q9b=datetime(2023,3,1)
q9list=[]
while q9a<=q9b:
 q9list.append(q9a.strftime('%d-%m-%Y'))
 q9a+=timedelta(days=1)

q9=pd.Series(q9list)
print(q9)

0     01-02-2023
1     02-02-2023
2     03-02-2023
3     04-02-2023
4     05-02-2023
5     06-02-2023
6     07-02-2023
7     08-02-2023
8     09-02-2023
9     10-02-2023
10    11-02-2023
11    12-02-2023
12    13-02-2023
13    14-02-2023
14    15-02-2023
15    16-02-2023
16    17-02-2023
17    18-02-2023
18    19-02-2023
19    20-02-2023
20    21-02-2023
21    22-02-2023
22    23-02-2023
23    24-02-2023
24    25-02-2023
25    26-02-2023
26    27-02-2023
27    28-02-2023
28    01-03-2023
dtype: object


In [10]:
"""10. Given a dictionary, convert it into corresponding dataframe and display it
dictionary = {'Brand': ['Maruti', 'Renault', 'Hyndai'], 'Sales' : [250, 200, 240]}"""
dictionary = {'Brand': ['Maruti', 'Renault', 'Hyndai'], 'Sales' : [250, 200, 240]}
q10=pd.DataFrame(dictionary,index=["Car 1","Car 2","Car 3"])
print(q10)

         Brand  Sales
Car 1   Maruti    250
Car 2  Renault    200
Car 3   Hyndai    240
